name: Generate gas report

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

jobs:
  reports:
    name: Gas report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Generate gas report
        uses: extractions/setup-just@v1
        run: just report

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: '.gas-report'
          message: Generate updated gas report
          default_author: user_info
