name: Generate documentation and gas report

on: [pull_request]

env:
  RPC_MAINNET_URL: ${{ secrets.RPC_MAINNET_URL }}
  FOUNDRY_PROFILE: ci

jobs:
  docs:
    name: Generate documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive

      - uses: actions/setup-node@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: npm install
        id: install

      - name: Install Modules
        run: npm run add
        id: add

      - name: Run Forge build
        run: |
          forge --version
          npm run build
        id: build

      - name: Generate gas report
        run: FOUNDRY_PROFILE=$FOUNDRY_PROFILE npm run doc

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: "docs"
          message: Generate updated docs
          default_author: github_actions
  reports:
    needs: docs
    name: Generate gas report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: npm install
        id: install

      - name: Install Modules
        run: npm run add
        id: add

      - name: Run Forge build
        run: |
          forge --version
          npm run build
        id: build

      - name: Generate gas report
        run: FOUNDRY_PROFILE=$FOUNDRY_PROFILE npm run report

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: ".gas-report"
          message: Generate updated gas report
          default_author: github_actions
