name: Generate gas report

on: [pull_request]

env:
  RPC_MAINNET_URL: ${{ secrets.RPC_MAINNET_URL }}
  FOUNDRY_PROFILE: ci

jobs:
  reports:
    name: Gas report
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Generate gas report
        run: make report

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: ".gas-report"
          message: Generate updated gas report
          default_author: user_info
