name: Reports

on: [pull_request]

env:
  RPC_MAINNET_URL: ${{ secrets.RPC_MAINNET_URL }}
  BLOCK_NUMBER: ${{ secrets.BLOCK_NUMBER }}
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Vertex gas report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive

      - uses: actions/setup-node@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: npm install
        id: install

      - name: Install Modules
        run: npm run add
        id: add

      - name: Run Forge build
        run: |
          forge --version
          npm run build
        id: build

      - name: Generate gas report
        run: npm run report

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: ".gas-report"
          message: Generate updated gas report
          default_author: github_actions
