name: Reports

on: [pull_request]

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  BLOCK_NUMBER: ${{ secrets.BLOCK_NUMBER }}

jobs:
  reports:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v2
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Dependencies
        run: npm install
      - name: Install Modules
        run: npm run add
      - name: Generate gas report
        run: npm run report
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: ".gas-report"
          message: Generate updated gas report
          default_author: github_actions
