name: Tests

on: [pull_request]

env:
  RPC_MAINNET_URL: ${{ secrets.RPC_MAINNET_URL }}
  BLOCK_NUMBER: ${{ secrets.BLOCK_NUMBER }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Dependencies
        run: npm install
      - name: Install Modules
        run: npm run add
      - name: Run Tests
        run: FOUNDRY_PROFILE=ci RPC_MAINNET_URL=$RPC_MAINNET_URL BLOCK_NUMBER=$BLOCK_NUMBER npm test
